# Jekyll configuration
#exclude:
#  - custom_components/
#  - repos/
exclude:
  - '.github/*'
  - 'automations/*'
  - 'configuration/*'
  - 'custom_components/*'
  - 'custom_templates/*'
  - 'dashboards/*'
  - 'esphome/*'
  - 'mocks_ci/*'
  - 'repos/*'
  - 'scenes/*'
  - 'scripts/*'

include:
  - '_config.yml'
  - 'README.md'
  - 'entities/*'
  - 'image/screenshot_card_scenes.png'
