- alias: Remote menu publish MQTT
  id: mqtt_remote_menu_publish
  description: ""
  mode: parallel
  max: 20
  triggers:
    - trigger: state
      entity_id: sensor.remote_menu_line_1
    - trigger: state
      entity_id: sensor.remote_menu_line_2
    - trigger: state
      entity_id: sensor.remote_menu_line_3
    - trigger: state
      entity_id: sensor.remote_menu_line_4
    - trigger: state
      entity_id: sensor.remote_menu_line_5
  conditions: []
  actions:
    - action: mqtt.publish
      metadata: {}
      data:
        evaluate_payload: false
        qos: "1"
        retain: false
        topic: homeassistant/remote_menu/line_{{ trigger.id }}
        payload: "{{ trigger.to_state.state }}"
