- platform: template
  fans:
    audio_cabinet:
      friendly_name: "Audio Cabinet Fan"
      value_template: "{{ states('light.outlet_audio_cabinet_fan') }}"
      percentage_template: "{{ state_attr('fan.esphome_web_e03714_fan_speed', 'percentage') if is_state('light.outlet_audio_cabinet_fan', 'on') else 0 }}"
      turn_on:
      - action: light.turn_on
        target:
          entity_id: light.outlet_audio_cabinet_fan
      - action: fan.turn_on
        target:
          entity_id: fan.esphome_web_e03714_fan_speed
      turn_off:
      - action: light.turn_off
        target:
          entity_id: light.outlet_audio_cabinet_fan
      - action: fan.turn_off
        target:
          entity_id: fan.esphome_web_e03714_fan_speed
      set_percentage:
      - action: "{{ 'light.turn_off' if(percentage == 0) else 'light.turn_on' }}"
        target:
          entity_id: light.outlet_audio_cabinet_fan
      - action: fan.set_percentage
        target:
          entity_id: fan.esphome_web_e03714_fan_speed
        data:
          percentage: "{{ percentage }}"
      preset_modes:
        - 'Manual'
        - 'Auto'
      preset_mode_template: "{{ 'Auto' if is_state('input_boolean.fan_audio_cabinet_auto', 'on') else 'Manual' }}"
      set_preset_mode:
        - action: "{{ 'input_boolean.turn_on' if(preset_mode == 'Auto') else 'input_boolean.turn_off' }}"
          target:
            entity_id: input_boolean.fan_audio_cabinet_auto
