- platform: template
  lights:
    volume_pioneer:
      friendly_name: "Pioneer Volume"
      icon_template: 'mdi:volume-high'
      value_template: >-
        {% if is_state('media_player.pioneer_onkyo', 'on') %}
          {% if state_attr('media_player.pioneer_onkyo', 'is_volume_muted') %}
            off
          {% else %}
            on
          {% endif %}
        {% else %}
          off
        {% endif %}
      turn_on:
        action: media_player.volume_mute
        target:
          entity_id: media_player.pioneer_onkyo
        data:
          is_volume_muted: false
      turn_off:
        action: media_player.volume_mute
        target:
          entity_id: media_player.pioneer_onkyo
        data:
          is_volume_muted: true
      set_level:
        action: media_player.volume_set
        target:
          entity_id: media_player.pioneer_onkyo
        data:
          volume_level: "{{ (brightness / 255 * 100)|int / 100 }}"
      level_template: >-
        {% if is_state('media_player.pioneer_onkyo', 'on') %}
          {{ (state_attr('media_player.pioneer_onkyo', 'volume_level')|float * 255)|int }}
        {% else %}
          0
        {% endif %}
    volume_bathroom:
      friendly_name: "Bathroom Volume"
      icon_template: 'mdi:volume-high'
      value_template: >-
        {% if is_state('media_player.pioneer_onkyo_zone_2', 'on') %}
          {% if state_attr('media_player.pioneer_onkyo_zone_2', 'is_volume_muted') %}
            off
          {% else %}
            on
          {% endif %}
        {% else %}
          off
        {% endif %}
      turn_on:
        action: media_player.turn_on
        target:
          entity_id: media_player.pioneer_onkyo_zone_2
      turn_off:
        action: media_player.turn_off
        target:
          entity_id: media_player.pioneer_onkyo_zone_2
      set_level:
        if: "{{ states('media_player.pioneer_onkyo_zone_2') != 'on' }}"
        then:
          action: media_player.turn_on
          target:
            entity_id: media_player.pioneer_onkyo_zone_2
        else:
          action: media_player.volume_set
          target:
            entity_id: media_player.pioneer_onkyo_zone_2
          data:
            volume_level: "{{ (brightness / 255 * 100)|int / 100 }}"
      level_template: >-
        {% if is_state('media_player.pioneer_onkyo_zone_2', 'on') %}
          {{ (state_attr('media_player.pioneer_onkyo_zone_2', 'volume_level')|float * 255)|int }}
        {% else %}
          0
        {% endif %}
    volume_bedroom:
      friendly_name: "Bedroom Volume"
      icon_template: 'mdi:volume-high'
      value_template: >-
        {% if is_state('media_player.pioneer_onkyo_zone_3', 'on') %}
          {% if state_attr('media_player.pioneer_onkyo_zone_3', 'is_volume_muted') %}
            off
          {% else %}
            on
          {% endif %}
        {% else %}
          off
        {% endif %}
      turn_on:
        action: media_player.turn_on
        target:
          entity_id: media_player.pioneer_onkyo_zone_3
      turn_off:
        action: media_player.turn_off
        target:
          entity_id: media_player.pioneer_onkyo_zone_3
      set_level:
        if: "{{ states('media_player.pioneer_onkyo_zone_3') != 'on' }}"
        then:
          action: media_player.turn_on
          target:
            entity_id: media_player.pioneer_onkyo_zone_3
        else:
          action: media_player.volume_set
          target:
            entity_id: media_player.pioneer_onkyo_zone_3
          data:
            volume_level: "{{ (brightness / 255 * 100)|int / 100 }}"
      level_template: >-
        {% if is_state('media_player.pioneer_onkyo_zone_3', 'on') %}
          {{ (state_attr('media_player.pioneer_onkyo_zone_3', 'volume_level')|float * 255)|int }}
        {% else %}
          0
        {% endif %}
